### ISSUE TITLE
add documentation about sample output_type to website 

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#107]
Once [the documentation about the new sample output_type format](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit) has been completed, it will need to be added to the documentation website. There currently is a [model output page](https://hubdocs.readthedocs.io/en/latest/user-guide/model-output.html) that may need to be re-thought or re-organized, as the samples documentation is long enough that it probably warrants its own page.

**Comment by mmkerr** [comment]
Are the notes above ready to be put into documentation or are there still outstanding issues/comments that need to be addressed?

**Comment by nickreich** [comment]
@mzorn-58 are there still comments that you need resolved in the google doc version of the content to be added?

**Comment by mzorn-58** [comment]
There are still a few comments on [the documentation about the new sample output_type format](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit) (pages 9-end).  Not sure if any text needs to be changed based on the comments.  I will start adding the text to hub doc early next week.
