### ISSUE TITLE
Add `Docson` widgets for documenting `JSON` Schema

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#12]
`Docson` provides a nice way for including interactive documentation of our JSON schema

### Resources
- [`Docson`](https://github.com/lbovet/docson)
- [Example of simple schema](http://lbovet.github.io/docson/index.html#/docson/examples/example.json)
- Example in the wild: [Global Coffee Data Standard](https://global-coffee-data-standard.readthedocs.io/en/latest/explanation.html#id4)

**Comment by annakrystalli** [comment]
Preview our schema in docson! http://lbovet.github.io/docson/index.html#https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/add-tasks-docs/tasks-schema.json

**Comment by annakrystalli** [comment]
Another real nice viewer but don't see us being able to integrate it: https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2FInfectious-Disease-Modeling-Hubs%2Fschemas%2Fmain%2Ftasks-schema.json

**Comment by nickreich** [comment]
@annakrystalli I think we can close this issue? feel free to reopen.
