### ISSUE TITLE
Hub-metadata file

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubDocs#24]
The directory structure specifies that admin.json and tasks.json should be JSON files, but model-metadata-schema.json can be a JSON or yaml file. 

Clarification is needed here.  At the very least, change to say "model-metadata-schema.{json,yml} is a JSON or YAML file". More generally, can we allow both formats for all 3 config files? If not, we should explain why?

**Comment by mzorn-58** [comment]
Will admin.json and tasks.json be able to be a YAML file?  If not, why not? [https://hubdocs.readthedocs.io/en/latest/format/hub-config.html](url)
