### ISSUE TITLE
hub-metadata-file.md

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubDocs#25]
admin.json detail and example needed.
tasks.json  detail needs to be reconciled with https://hubdocs.readthedocs.io/en/latest/_static/docson/index.html#https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/tasks-schema.json$$expand and an example provided.

**Comment by mzorn-58** [comment]
Looks like example has been added. 
https://hubdocs.readthedocs.io/en/latest/format/hub-config.html
 Can issue be closed?
