### ISSUE TITLE
"suggest an edit" doesn't have the right directory path

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#31]
I think there is a missing "source" in the path where this "suggest an edit" link is looking
<img width="186" alt="image" src="https://user-images.githubusercontent.com/1280767/230168246-c2a270a4-5374-4cdc-8377-0801a3ef4895.png">
Gives the error:
```
The 'Infectious-Disease-Modeling-Hubs/hubDocs' repository doesn't contain the 'docs/index.md' path in 'main'.  
```

**Comment by micokoch** [comment]
I think the correct link should be:
https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/edit/main/docs/source/index.md

**Comment by micokoch** [comment]
https://github.com/micokoch/hubDocs/blob/main/docs/source/conf.py
