### ISSUE TITLE
schema blocks in model-metadata could use clearer labeling.

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubDocs#33]
on the [model_metadata](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/blob/main/docs/source/format/model-metadata.md) page,  there are two blocks after the "Template metadata schema file" section header. The first, which looks fine, contains the various fields. The second looks almost as if it's a YAML version of a json-schema file - I'm not sure what it is. Both could use better introduction and clarity on what they represent and how they should be used.

**Comment by mzorn-58** [comment]
Can someone provide some text?

**Comment by micokoch** [comment]
In [#91], I added text to clarify what the files are, and kept only the JSON files. I hope this is adequate, but please reopen if you think more explanations are needed.
