### ISSUE TITLE
Bin-prop needs to be more clearly explained in Model Output page

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubDocs#34]
In the [model output page](https://hubdocs.readthedocs.io/en/latest/format/model-output.html) there is a table with a list of output types, followed by an example output table. The example table contains rows with type "bin_prob", even though "bin_prop" is not listed as one of the types in the first table... Would be clearer if bin_prop was introduced with the other types.

**Comment by micokoch** [comment]
Changed `bin_prob` to `pmf` in the example.
https://github.com/micokoch/hubDocs/blob/main/docs/source/format/model-output.md
