### ISSUE TITLE
Target data might benefit from an example 

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubDocs#35]
The [target data](https://hubdocs.readthedocs.io/en/latest/format/target-data.html)  page would benefit from an example of model output, truth data, and how they might be matched.

**Comment by mzorn-58** [comment]
get examples from [slides](https://hubdocs.readthedocs.io/en/latest/format/model-output.html)

**Comment by mzorn-58** [comment]
closing this.  SOme documentaiton is in https://hubdocs.readthedocs.io/en/latest/user-guide/target-data.html.

Also discussion about target data in general [here](https://github.com/orgs/Infectious-Disease-Modeling-Hubs/discussions/9#discussioncomment-8944609)
