### ISSUE TITLE
Define when separate model_task blocks are required

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#38]
Two situations:
1. All targets in one model_tasks block must be able to be expressed by the same output_types with the same parameters.”
2.  all target/output type combinations in the same model tasks block have the same combination of required and optional values for all task id and output type/output id variables

**Comment by mzorn-58** [comment]
Update [https://hubdocs.readthedocs.io/en/latest/format/model-output.html](url)

**Comment by mzorn-58** [comment]
Fixed here https://hubdocs.readthedocs.io/en/latest/user-guide/model-output.html
