### ISSUE TITLE
update output_type

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#50]
On this page we need to update to change type--> output type in a few places.
https://hubdocs.readthedocs.io/en/latest/format/model-output.html

**Comment by annakrystalli** [comment]
And and mention of `type_id` to `output_type_id`.

Initial issues: https://github.com/Infectious-Disease-Modeling-Hubs/schemas/issues/49

**Comment by micokoch** [comment]
I hope I'm not missing anything, but I think this is complete [here](https://github.com/micokoch/hubDocs/blob/main/docs/source/user-guide/model-output.md). Could be closed when eventually updated.
