### ISSUE TITLE
Source info from slides to provide higher level background to docs

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#52]
Inspired by the slides from the recent presentation, it could be really nice to add some of the information in the slides as additional background in our docs.

In particular I feel the slide sections on:

-  overall motivation behind hubs
- their evolution 
- info on types of hubs (i.e. distinction between forecasting, nowcasting, scenarios etc)

would add useful context to the project in our docs.

**Comment by nickreich** [comment]
Here is a link to the "published" slides that we could incorporate. https://docs.google.com/presentation/d/e/2PACX-1vRhXa7DgUDATi3Ovzc8rmUADD9aWeaZKkDV-2wXmja4KT0PJV7elsWiNRHCj9ypRaFEGoFNumOP2mhS/pub?start=false&loop=false&delayms=60000&slide=id.p

**Comment by mzorn-58** [comment]
Figure out what to include from [slides](https://docs.google.com/presentation/d/e/2PACX-1vRhXa7DgUDATi3Ovzc8rmUADD9aWeaZKkDV-2wXmja4KT0PJV7elsWiNRHCj9ypRaFEGoFNumOP2mhS/pub?start=false&loop=false&delayms=3000&slide=id.g20a596752b5_0_151)

**Comment by micokoch** [comment]
Added selected information and slides on PR #112 . If PR is approved, will close this issue.
