### ISSUE TITLE
add invitation for collaboration and coordination on software page

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#53]
To try to avoid duplicative efforts, we should add some language on the software page that both invites collaboration and initial discussion for possible collaborators to make sure that new ideas are brought in appropriately.

**Comment by mzorn-58** [comment]
Suggest some text for software page (see how to contribute for some verbiage)

**Comment by mzorn-58** [comment]
Added text to [contribute](https://hubdocs--63.org.readthedocs.build/en/63/overview/contribute.html) page
