### ISSUE TITLE
Update example related to simple forecast hub to match updated specification there

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubDocs#56]
We changed the example simple forecast hub to work with covid forecasts instead of flu forecasts, and made a few other minor updates as part of that.  We should update the description of examples in the Overview > Running examples section to reflect these changes.

**Comment by micokoch** [comment]
I updated the hubDocs information on the simple forecast hub to match the example and csv file in the repository [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/55/commits/6aaaab4e05faaa3afa98416d3618b25165ffed7e) https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/55/commits/6aaaab4e05faaa3afa98416d3618b25165ffed7e and [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/55/commits/7627ce00c7c13f83255f93e9dd257117abb5ad9f) https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/55/commits/7627ce00c7c13f83255f93e9dd257117abb5ad9f
These and more changes are in PR https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/55

**Comment by mzorn-58** [comment]
Can this issue be closed?
