### ISSUE TITLE
Add Prerequisites section

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#57]
Would be good to have a section in the docs, probably quite early on, about prerequisite knowledge of skills / tools required to:
- set up a hub
- submit to a hub?
- access data from a hub?

**Comment by mzorn-58** [comment]
Done in[ quickstart](https://hubdocs.readthedocs.io/en/latest/quickstart-hub-admin/intro.html)
