### ISSUE TITLE
Document which configurations might be difficult to change down the line

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#58]
Might be good idea to mention what type of changes would be difficult to make once a hub is up an running and has collected some data and would therefore require extra care to get right at the beginning.

This might be a bit unsatisfactory and approaches to accommodate larger changes that might invalidate previous round data.

Functionality to check whether any new changes to the tasks.json would invalidate previous data might be a good starting place

**Comment by mzorn-58** [comment]
@annakrystalli Does [this](https://hubdocs.readthedocs.io/en/latest/user-guide/hub-config.html) have enough info or should more be added?

**Comment by annakrystalli** [comment]
Probably, There's nothing that jumps out to me that needs adding
