### ISSUE TITLE
consider adding a new section to the Overview describing data storage options

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubDocs#62]
I think there are three supported options for data storage/archival now:

- GitHub repositories
- AWS buckets
- Zoltar

Maybe we can add a new page under the Overview heading in the documentation with a paragraph or two describing each of these options?

related to #32

**Comment by mzorn-58** [comment]
created a [page ](https://github.com/micokoch/hubDocs/blob/main/docs/source/overview/data-storage.md)for data storage.  Any suggestions for text???

**Comment by micokoch** [comment]
Hello. I edited the text to make it shorter (and have all three about equally long), and added a definition for Zoltar [here](https://github.com/micokoch/hubDocs/blob/main/docs/source/overview/definitions.md). I think that's enough for now, but if you want it longer we can reopen this issue.
