### ISSUE TITLE
somes links cannot be displayed due to the way how to specify md reference 

### ISSUE THREAD

**Issue by kjsato** [Infectious-Disease-Modeling-Hubs/hubDocs#68]
somes links cannot be displayed due to the way how to specify md reference, inc. in-page links when building htmls pages

- warnings generated but actually link information have been lost in HTMLs

when building htmls with `make html`:
```
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/setting-up.md:15: WARNING: 'myst' 参照先が見つかりません(it means "reference not found"): #hub_admin_config
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:3: WARNING: 'myst' 参照先が見つかりません: #model_tasks_schema
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:13: WARNING: 'myst' 参照先が見つかりません: #model_tasks_schema
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:31: WARNING: 'myst' 参照先が見つかりません: #clone_repo
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:41: WARNING: 'myst' 参照先が見つかりません: ../user-guide/tasks.md#usage-of-task-id-variables
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:44: WARNING: 'myst' 参照先が見つかりません: ../user-guide/model-output.md#formats-of-model-output
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:76: WARNING: 'myst' 参照先が見つかりません: ../user-guide/model-output.md#formats-of-model-output
> /Users/koji/Codes/smh/hubDocs/docs/source/quickstart-hub-admin/tasks-config.md:77: WARNING: 'myst' 参照先が見つかりません: ../user-guide/model-output.md#formats-of-model-output
```

**Comment by micokoch** [comment]
Hello @kjsato. Have you tried building with:
`make clean && make html`
It looks like a problem I've had before, and this fixed it.
Let me know if it doesn't work. Thanks!

**Comment by kjsato** [comment]
@micokoch I tried those but the result was the same (references are not found)
If it had already fixed, please update `main` or create another branch with it then I'd like to catch it to try.

In addition, we would appreciate it if you could also reflect the result on the live document set. E.g., in
https://hubdocs.readthedocs.io/en/latest/quickstart-hub-admin/tasks-config.html
we can see missing links on it

**Comment by micokoch** [comment]
Hi @kjsato . I think I fixed all the broken links in [this build](https://hubdocs--74.org.readthedocs.build/en/74/index.html). Once the PR is approved, it should be reflected on the live document.
If this works for you, then maybe we can close this issue. Thank you.
