### ISSUE TITLE
Modify documentation for tasks.json

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubDocs#69]
For targets like peak size, this is not related to time points, so there is no horizon or target date.  So in the submission file, you should put NA in those columns.  But in the tasks.json, you can put either null or NA 
Currently you could put required = null, optional = null and this will pass the validation (incorrectly).
Fix this in validations for tasks.json file (it should not say a tasks.json with both required=null and optional=null passes)

- [ ] Document in hubDocs

**Comment by mzorn-58** [comment]
Does the above mean that [5.5 ](https://hubdocs.readthedocs.io/en/latest/quickstart-hub-admin/tasks-config.html#required-and-optional-elements) needs to be updated to remove the last sentence?

**Comment by LucieContamin** [comment]
@annakrystalli  corrects me if I am wrong but we made an update to allow the required = null, optional = null for this kind of target and this will pass the validation. It is the expected behavior

**Comment by LucieContamin** [comment]
Sorry I miss that issue, I think we can close it now.
