### ISSUE TITLE
clarify documentation in hub-metadata.md

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#7]
Need more distinction between and instructions for the schema file and the actual metadata json files. e.g., right now, I think an example (in yaml?) for the schema file is given, but not an actual hub-meta.json file.

**Comment by mzorn-58** [comment]
Looks like this has been resolved. [https://hubdocs.readthedocs.io/en/latest/format/model-metadata.html](https://github.com/orgs/Infectious-Disease-Modeling-Hubs/projects/3/views/url)

Can this issue be closed?
