### ISSUE TITLE
how to specify time units when setting up "horizon"

### ISSUE THREAD

**Issue by kjsato** [Infectious-Disease-Modeling-Hubs/hubDocs#70]
in 5.3 Setting up the "horizon":

- The horizon refers to the difference between the target_date and the origin_date in time units specified by the hub (these could be days, weeks, or months).

Is it necessary to add an explanation of how to specify the time unit when specifying the horizon?

**Comment by LucieContamin** [comment]
It sounds good to me, thanks! I guess we should also add example for a `target_date`/`target_end_date` column.

**Comment by nickreich** [comment]
@LucieContamin are you actively working on this, or can/should we assign someone else who works on documentation?

**Comment by LucieContamin** [comment]
I apologize, I forgot I assigned myself.  Someone else can work on it, I will not have the time in the next week, sorry about that

**Comment by mzorn-58** [comment]
@LucieContamin and I consider issue closed
