### ISSUE TITLE
A Supplementary explanation be added before installing hubUtils in "Validating your config files"

### ISSUE THREAD

**Issue by kjsato** [Infectious-Disease-Modeling-Hubs/hubDocs#71]
In this section any other information such as "in R console", or "using RStudio" has not been given, users can see "you need to install".  How about adding some additional explanation?

**Comment by mzorn-58** [comment]
[pr#73](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/73) addresses this
