### ISSUE TITLE
validating config files description

### ISSUE THREAD

**Issue by kjsato** [Infectious-Disease-Modeling-Hubs/hubDocs#72]
In the description of "Validating your config files", we might understand the two config files were validated with one command but actually only one file "tasks.json" had been validated. If it is true, the description should be modified according to the actual behaviour so far.

**Comment by mzorn-58** [comment]
@lshandross @LucieContamin @annakrystalli @elray1 

Does the following code validate both "tasks.json" and "admin.json" or just "tasks.json"?


```
library(hubUtils)
validate_config(
    hub_path = ".",
    config = c("tasks", "admin"), 
    config_path = NULL, 
    schema_version = "from_config", 
    branch = "main"
)
```

**Comment by mzorn-58** [comment]
SO we should change `config=c("tasks","admin") ` to read `config = "tasks"`.  And then we could add a note below saying that you you would use `validate_hub_config()` and  `config=c("tasks","admin") ` to validate all config files.

**Comment by annakrystalli** [comment]
Ho @mzorn-58 `validate_hub_config()` takes no arguments, it just validates all hub config files in one go. 

Also both these functions now live in the `hubAdmin` package. See function documentation pages for more details including examples of how both functions are used:
- https://infectious-disease-modeling-hubs.github.io/hubAdmin/reference/validate_hub_config.html
- https://infectious-disease-modeling-hubs.github.io/hubAdmin/reference/validate_config.html

**Comment by mzorn-58** [comment]
@micokoch Is it OK if I work on this Alvaro?  I am looking for an issue and I had done some work on this previously.

**Comment by micokoch** [comment]
Yes, @mzorn-58 - thank you.
