### ISSUE TITLE
check that description of cdf format is consistent with other formats

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#75]
https://hubdocs.readthedocs.io/en/latest/user-guide/model-output.html#formats-of-model-output

Noting a small point of confusion. I was surprised to see that 
- the quantile-level was in `output_type_id` and the quantile forecast in `value`
- the x-value for the cdf was in `output_type_id` and the cdf in `value`. 
To me it felt a bit inconsistent that the "real world value" was once in `value` and once in `output_type_id`. I'm sure there are good reasons for this, just noting it in case it is useful as feedback. 

<img width="605" alt="image" src="https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/assets/37978797/38588997-9eda-484d-ad44-caa52e0a07e3">

_Originally posted by @nikosbosse in https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/discussions/125#discussioncomment-7575266_

**Comment by aaronger** [comment]
https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/discussions/125#discussioncomment-7622142

**Comment by nickreich** [comment]
NVM - this is a non-issue afterall. See 
https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/discussions/125#discussioncomment-7626164
