### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubDocs#76]
Use definition below
[Definitions of roles](https://r-pkgs.org/description.html#sec-description-authors-at-r) (Author, maintainer, contributor, etc…)

Going forward, ensure that PRs from new contributors include an update to authorship roles (for R packages, in description file)

**Comment by mzorn-58** [comment]
@annakrystalli I am pretty sure you did some work on this.  Do we need to add anything to hubverse documentation?

**Comment by annakrystalli** [comment]
I updated all the R packages but not sure how to add authors to the readthedocs framework. Might need some research

**Comment by mmkerr** [comment]
@nickreich Martha and I revisited this issue. We wanted to make package authorship visualization more consistent. Under ‘software’, if you click on the name of a package it usually brings you to a repo (except for HubUtils). To the right of the package repo page, contributors are usually listed. hubAdmin and hubData are missing info on contributors.
Our questions were:
1. Is it sufficient to list authors as contributors on the package repo, or should authorship also be listed somewhere else (authorship is also listed on the description file in the package repo).
2. There are some situations where the authorship in the description file is not the same as the contributors (e.g. hubValidations). Is this an issue?
3. Should we add contributors for hubAdmin and hubData based on the description file in their respective repos?

**Comment by annakrystalli** [comment]
Hi @mmkerr 

Just a note that the authors are not missing on `hubData` and `hubAdmin`. You just need to click to expand to the full list of contributors https://infectious-disease-modeling-hubs.github.io/hubData/authors.html

**Comment by annakrystalli** [comment]
Also, at least in R packages, this info is auto-generated from the DESCRIPTION file so is always consistent with the information there and follows standard R convention for displaying contribution.

**Comment by mmkerr** [comment]
Thanks @annakrystalli . I'll go ahead and close this.
