### ISSUE TITLE
Add text how to get involved

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubDocs#78]
Add text to readmes and documentation sites about how to get involved (github links, email group link) to bottom of readmes

## Become Hubverse Community Member
This group is for announcing new features in the Hubverse to the user community. If you would like to become a Hubverse community member, go to [hubverse@groups.io](https://groups.io/g/hubverse) and click on the **+Apply for Membership in this group** on bottom left hand side of the page.

**Comment by micokoch** [comment]
I believe this is completed now in the contact and contribute pages in [the most recent PR](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/74). You can close this issue (I can't).

**Comment by mmkerr** [comment]
@mzorn-58 Can I help with this? What readmes does this text need to be added to?

**Comment by mzorn-58** [comment]
see https://reichlab.slack.com/archives/C02QMRCGA4F/p1701371649723379
