### ISSUE TITLE
 No mention of using explicit end & start date when configuring "submission_due"  on page /quickstart-hub-admin/tasks-config.html

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#82]
In the [Setting up `"submission_due"`](https://hubdocs.readthedocs.io/en/latest/quickstart-hub-admin/tasks-config.html#setting-up-submissions-due) section, there is no mention of setting up rounds with explicit end & start date submission windows instead of submission windows relative to a reference date.

See schema for details:

https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/de580d56b8fc5c24dd36a32994182e37b8b0ac95/v2.0.0/tasks-schema.json#L1323-L1380

**Comment by micokoch** [comment]
Explained this more clearly in [PR#82](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/84). If that seems okay to you (and once the PR is merged), we can close this issue.
