### ISSUE TITLE
finish hub model task metadata documentation

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#9]
https://hubdocs.readthedocs.io/en/latest/format/hub-metadata.html#hub-model-task-metadata-hub-tasks-file

From @elray1 : "what's the best way to document this?"

**Comment by mzorn-58** [comment]
Looks like this has been resolved. [https://hubdocs.readthedocs.io/en/latest/format/model-metadata.html](url)

**Comment by nickreich** [comment]
Agree that these comments feel like from an earlier era.
