### ISSUE TITLE
Add hubData and hubAdmin to sofware page

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubDocs#93]
Issue on page /user-guide/software.html

Need to add `hubData` and `hubAdmin` details and update `hubUtils` description

Could just copy content from discussion topic https://github.com/orgs/Infectious-Disease-Modeling-Hubs/discussions/8

**Comment by micokoch** [comment]
Updated all references to hubUtils in PR #101.
