### ISSUE TITLE
update overview data figure

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubDocs#95]
Looking at the figure here: https://hubdocs.readthedocs.io/en/latest/user-guide/tasks.html#task-id-variables

 - Update "truth" to "target"
 - Once we've finalized how we're thinking about target data, update.  It's looking likely that we will ask the hub to provide two versions of target data, long form and with target values.  We might remove the "calculate" box between those.
 - Maybe add a color code for "hubverse provides" and use that color for "calculate scores"?
 - It may or may not be helpful to add a more complete view of the setup and other steps including, e.g. validating submissions and building ensembles?

**Comment by nickreich** [comment]
@elray1 do you have the original source for this figure?

**Comment by elray1** [comment]
it's defined here: https://lucid.app/lucidchart/637de8d8-ba72-4182-9eb9-a11066a266b6/edit?invitationId=inv_d79c320f-6d72-466a-b188-e0d6c3256547#
