### ISSUE TITLE
consider naming `reference_date` as a possible standard task id field name

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubDocs#97]
Looking at this page: https://hubdocs.readthedocs.io/en/latest/user-guide/tasks.html#usage-of-task-id-variables

We describe `origin_date` there, but subsequent discussions in some hubs have led to the also-reasonable choice of `reference_date` for the name of this variable.

**Comment by mzorn-58** [comment]
see https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/126

**Comment by mzorn-58** [comment]
PR [#126](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/126) merged
